---
title: "main"
output: html_document
---

```{r, message=FALSE, warning=FALSE}
source("cod/setup.R")
runApp('cod')
```

```{r}
fig <- ggplot() +
  geom_line(
    data = renta_permanente(c(1e6, 2e6, 5e6), 65, 38e6, 0, 0.036),
    aes(x = edad, y = pension, color = "Tasa fija 3.6%"),
    linewidth = 1
  ) +
  geom_line(
    data = renta_permanente(c(1e6, 2e6, 5e6), 65, 38e6, 0, intereses(65)),
    aes(x = edad, y = pension, color = "Tasa variable"),
    linewidth = 1
  ) +
  scale_color_manual(
    name = "Escenarios",
    values = c(
      "Tasa fija 3.6%" = "darkorange",
      "Tasa variable" = "darkgreen"
    )
  ) +
  labs(
    title = "Trayectorias del monto de pensión",
    x = "Edad",
    y = "Monto de la pensión"
  ) +
  theme_minimal()
ggplotly(fig)
```


```{r}
x <- 65
sim <- sapply(1:1000, function(x) renta_permanente(c(1e6,2e6,5e6), 65, 38e6, 2025, intereses(65))$Pension_Mensual/1e3)
df_res <- data.frame(Tiempo = x:115,
                     Media = sapply(1:51, function(y) mean(sim[y,])),
                     IC_inf = sapply(1:(115-x+1), function(y) quantile(sim[y,], 0.05)),
                     IC_sup = sapply(1:(115-x+1), function(y) quantile(sim[y,], 0.95)))
```

```{r}
df_sim <- as.data.frame(sim)
df_sim$Tiempo <- 1:nrow(sim) + x - 1
df_long <- pivot_longer(df_sim, -Tiempo, names_to = "Simulacion", values_to = "Pension")

df_long <- df_long %>%
  mutate(Tipo = "Simulaciones")

df_res_lineas <- df_res %>% mutate(Tipo = "Media")

fig <- ggplot() +
  geom_line(data = df_long,
            aes(x = Tiempo, y = Pension, group = Simulacion, color = "Simulaciones"),
            alpha = 0.2, linewidth = 0.2) +
  geom_ribbon(data = df_res, 
              aes(x = Tiempo, ymin = IC_inf, ymax = IC_sup, fill = "IC"),
              alpha = 0.3) +
  geom_line(data = df_res_lineas, 
            aes(x = Tiempo, y = Media, color = "Media"),
            linewidth = 1) +
  geom_hline(aes(yintercept = 30.63835, color = "Monto"),
             linetype = "dashed", linewidth = 0.8) +
  scale_color_manual(name = "",
                     values = c(
                       "Media" = "red",
                       "Simulaciones" = "blue",
                       "Monto mínimo" = "black"
                     )) +
  scale_fill_manual(name = "", values = c("IC" = "green")) +
  labs(title = "Trayectorias simuladas del monto de pensión en miles",
       x = "Edad", y = "Monto de la pensión") +
  theme_minimal() 
p <- ggplotly(fig)

for(i in seq_along(p$x$data)) {
  nm <- p$x$data[[i]]$name
  p$x$data[[i]]$name <- sub("^\\(([^,]+),.*\\)$", "\\1", nm)
}
p


```

